export const productCopy = {
  displayName: "本地陪伴体",
  positioning: "一个本地优先的陪伴助手，会记住重要的事，帮你接住上下文。",
  promise: "我会长期记住重要的事，陪你把每天接上；记忆留在本机，可查看、可撤回。",
  coreValues: [
    {
      title: "长期陪伴",
      description: "下次再见时，我能接住你之前说过的重要事。",
    },
    {
      title: "本地记忆",
      description: "值得留下的内容优先保存在这台电脑里。",
    },
    {
      title: "记忆可控",
      description: "记住了什么、为什么记住、能不能撤回，都让你看得见。",
    },
  ],
  firstUse: {
    title: "今天想让我从哪里陪你继续？",
    description: "只说一件正在发生的事就可以开始，其他内容以后再补。",
    question: "今天想让我从哪里陪你继续？",
    placeholder: "例如：我最近在准备一件重要的事，想有人帮我接着记住。",
    submitLabel: "开始聊天",
    skipLabel: "先直接聊",
    completedMessage: "我会按规则整理这次内容，你之后可以在记忆里查看和撤回。",
  },
  memoryPage: {
    title: "记忆工作台",
    description: "档案、图谱、日记和资料都在这里，你可以查看、搜索、整理和改正。",
    primaryPanelTitle: "先看这三件事",
    primaryPanelDescription: "记忆留在本机，重要内容可见、可确认，也能随时撤回。",
    searchPlaceholder: "搜索我记住的事",
    activeSectionTitle: "我现在记得什么",
    pendingSectionTitle: "等你确认",
    recentHistoryTitle: "随时改正或忘记",
    emptyState: "还没有值得长期记住的事。你可以先告诉我一个偏好或正在做的项目。",
    advancedReviewTitle: "回顾与整理建议",
    advancedReviewDescription: "生成回顾、查看整理建议和本机积累；默认只读，不打扰日常聊天。",
    advancedManagementTitle: "高级记忆管理",
    advancedManagementDescription: "用于检查、备份和处理更多记录，默认不打扰日常使用。",
  },
  chatPage: {
    title: "聊天",
    description: "直接和我说话；重要的事我会按规则整理，之后可在记忆里查看和撤回。",
    inputPlaceholder: "和我说说现在发生的事...",
    quickPrompts: [
      "我今天有点累",
      "记住我最近在准备一件重要的事",
      "明天提醒我继续这件事",
      "帮我回顾今天",
    ],
  },
  home: {
    stageLabel: "Agent Pet 首页舞台",
    statusModelTitle: "对话能力",
    statusKnowledgeTitle: "记忆与资料",
    recentActivityTitle: "最近帮你整理",
    connectionAndDataTitle: "连接与数据",
    quickPrompts: [
      "告诉你今天的一件事。",
      "让你记住一个偏好。",
      "明天提醒我继续。",
    ],
  },
  worldPage: {
    tabLabel: "记忆",
    eyebrow: "记忆工作台 / 资料库",
    title: "资料库",
    description: "把文档、链接和想法整理成以后能找回的资料；这是记忆工作台的一部分。",
  },
  settingsPage: {
    eyebrow: "基础设置",
    title: "把 Agent Pet 调成适合你的工作方式。",
    description: "这里管理它怎么聊天、把记忆保存在哪里、什么时候自动整理，以及是否朗读回复。",
    stepConnect: "连接对话能力",
    stepSave: "选择保存位置",
    stepAutomation: "设置自动整理",
    stepVoice: "调整语音与高级项",
    testConnection: "测试对话能力",
    refresh: "刷新状态",
    advancedModelTitle: "高级：能力分工",
    advancedModelDescription: "可选给不同能力单独设置模型；大多数用户保持默认即可。",
  },
} as const;
