export const CHAT_STREAM_WATCHDOG_TIMEOUT_MS = 14_000;
export const PET_BUBBLE_ACTION_WATCHDOG_TIMEOUT_MS = 14_000;
export const PET_BUBBLE_ERROR_HIDE_DELAY_MS = 10_000;
export const PET_BUBBLE_STOPPED_HIDE_DELAY_MS = 5_000;
